# MASTERARBEIT DARWIN 
#-------------------------------------------------------------------------------
if (!require(MASS)) install.packages("MASS"); library(MASS)
if (!require(ggplot2)) install.packages("ggplot2"); library(ggplot2)
if (!require(foreach)) install.packages("foreach"); library(foreach)
if (!require(doParallel)) install.packages("doParallel"); library(doParallel)
if (!require(tictoc)) install.packages("tictoc"); library(tictoc)
setwd(file.path(dirname(rstudioapi::getActiveDocumentContext()$path)))
source("utils_functions.R") # Upload functions in separate script
set.seed(1234)# set seed for replication
#-------------------------------------------------------------------------------
# SIMULATION OF GRID

xdim = 30 # horizontal size
ydim = 30 #vertical size

# Erzeugt zufällige Koordinaten im Bereich [0, 1] für das Raster
grid = data.frame(x = runif(xdim, 0, 1), y = runif(ydim, 0, 1))
#-------------------------------------------------------------------------------
plot(grid$x, grid$y, 
     main = "Spatial Locations Generated by Random Uniform Distribution",
     xlab = "x-coordinate", ylab = "y-coordinate",
     pch = 16, col = "blue")
text(grid$x, grid$y, labels = 1:nrow(grid), pos = 3, cex = 0.7, col = "red")
#-------------------------------------------------------------------------------
# GENERATE TRUE ANALYTICAL COVARIANCE
#-------------------------------------------------------------------------------

sigma = 1
phi = 1/3
true_covariance = cov_exponential(grid, sigma, phi, method = "euclidean")

#-------------------------------------------------------------------------------
#sigma = 1
#a = 0.1
#c = 0.5
#beta = 0
#true_covariance_gn <- cov_gneiting(grid,sigma, a, c,beta,method = "difference")

#-------------------------------------------------------------------------------

#Check covariance is positive semidefinite
is_positive_semi_definite(true_covariance)

#-------------------------------------------------------------------------------
# SIMULATE SPATIAL GAUSSIAN RANDOM FIELD
X = mvrnorm(n = 1, mu = rep(0, nrow(grid)), Sigma = true_covariance)
grid$sim = X

#Plot the process where the colors indicate the value of the spatial process
ggplot(grid, aes(x = x, y = y, color = sim)) +
  geom_point(size = 5) +
  scale_color_gradient(low = "blue", high = "red") +
  labs(title = "Simulated Spatial Data", x = "X Coordinate", y = "Y Coordinate",
       color = "Value") +
  theme_minimal()

#-------------------------------------------------------------------------------
# ESTIMATE SPATIAL COVARIANCE

bandwidth = 0.21 # Beispiel-Bandbreite

#kernel = "gaussian_kernel"
#kernel = "epanechnikov_kernel"
#kernel = "rechteck_kernel"
kernel = "triangle_kernel"

tic("matrix cov estimation")
est_cov_matrix = matrix(NA, nrow = nrow(grid), ncol = nrow(grid))
est_corr_matrix = matrix(NA, nrow = nrow(grid), ncol = nrow(grid))

for(i in 1:nrow(grid)) {
  for(j in 1:nrow(grid)) {
    est_cov_matrix[i,j] = kernel_cov_vec(as.numeric(grid[i, 1:2]),
                                     as.numeric(grid[j, 1:2]),
                                     X, grid[,1:2],
                                     bandwidth, kernel)$covariance
  }
}
toc()

is_positive_semi_definite(est_cov_matrix)

tic(" auto matrix cov estimation")
# Berechne die Autokorrelationsmatrix
for(i in 1:nrow(grid)) {
  for(j in 1:nrow(grid)) {
    est_corr_matrix[i,j] = est_cov_matrix[i,j] / 
      sqrt(est_cov_matrix[i,i] * est_cov_matrix[j,j])
  }
}
toc()


# Prüfen, ob die Diagonalelemente 1 sind
diag(est_corr_matrix)

is_positive_semi_definite(est_corr_matrix)


#-------------------------------------------------------------------------------
# Norm 12.17411
norm(est_cov_matrix - true_covariance, type = "2")

#-------------------------------------------------------------------------------
# Norm with autokorellation
norm(est_corr_matrix - true_covariance, type = "2")





